#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

// set is always zero, binding is always the same index as the buffer in the pipeline creation struct
layout(set = 0, binding = 0, std430) buffer Positions
{
    vec2 pos[];
} positions;

void main()
{
    vec2 current_pos = positions.pos[gl_GlobalInvocationID.x];
    positions.pos[gl_GlobalInvocationID.x] = current_pos - vec2(1.0, 1.0);
}